// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Configurable.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public Subsystem//, public Configurable
{
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	float HighSpeedRate;
	float LowSpeedRate;
	float leftMotorOutput;
	float rightMotorOutput;

	bool LeftMotor1_Enabled;
    int  LeftMotor1_CANID;
    bool LeftMotor1_Reversed;

	bool LeftMotor2_Enabled;
    int  LeftMotor2_CANID;
    bool LeftMotor2_Reversed;

	bool LeftMotor3_Enabled;
    int  LeftMotor3_CANID;
    bool LeftMotor3_Reversed;

	bool RightMotor1_Enabled;
    int  RightMotor1_CANID;
    bool RightMotor1_Reversed;

	bool RightMotor2_Enabled;
    int  RightMotor2_CANID;
    bool RightMotor2_Reversed;

	bool RightMotor3_Enabled;
    int  RightMotor3_CANID;
    bool RightMotor3_Reversed;


public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANJaguar* leftMotor1;
	CANJaguar* rightMotor1;
	CANJaguar* leftMotor2;
	CANJaguar* rightMotor2;
	RobotDrive* driveA;
	CANJaguar* leftMotor3;
	CANJaguar* rightMotor3;
	RobotDrive* driveB;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveTrain();

//	virtual void RetrieveConfig();
//	virtual void StoreConfig();
//	virtual void Configure();

	void InitDefaultCommand();
	void SetDrive_Arcade(float x, float y, bool highRate = false);
	void Set_VoltageMode();
	void Stop();
	float Limit(float num);

};

#endif
