// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.




#include "Horn.h"
#include "../Robotmap.h"

Horn::Horn() : Subsystem("Horn") {
	printf("Entering Horn Constructor\n");
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	spike = RobotMap::hornSpike;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	printf("Exiting Horn Constructor\n");
}
    
void Horn::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
/*
void Horn::RetrieveConfig()
{
	// do nothing
}

void Horn::StoreConfig()
{
	// do nothing
}

void Horn::Configure()
{
	// do nothing
}
*/
void Horn::On()
{
	spike->Set(Relay::kForward);
}

void Horn::Off()
{
	spike->Set(Relay::kOff);
}
