// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef LIFTER_H
#define LIFTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Configurable.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Lifter: public Subsystem//, public Configurable
{
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	bool forwardIsUp;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DoubleSolenoid* solenoid;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Lifter();
	//virtual void RetrieveConfig();
	//virtual void StoreConfig();
	//virtual void Configure();

	void InitDefaultCommand();

	void LiftUp();
	void LiftDown();
	float Limit(float num);
};

#endif
