// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "ChargeShooter.h"

ChargeShooter::ChargeShooter() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	count = 0;
	doRun = true;
}

// Called just before this Command runs the first time
void ChargeShooter::Initialize() {
	count = 0;
	doRun = true;
}

// Called repeatedly when this Command is scheduled to run
void ChargeShooter::Execute() {
	if (doRun)
	{
		Robot::shooter->solenoid->Set(true);
		Wait(0.5);
		count++;
	}
}

// Make this return true when this Command no longer needs to run execute()
bool ChargeShooter::IsFinished() {
	if (count == 6)
	{
		doRun = false;
		count = 0;
	    return true;
	}
	return false;
}

// Called once after isFinished returns true
void ChargeShooter::End() {
	Robot::shooter->solenoid->Set(false);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ChargeShooter::Interrupted() {

}
