// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ChargeShooter.h"
#include "Commands/Fire.h"
#include "Commands/NextTube.h"
#include "Commands/PrevTube.h"
#include "Commands/Release.h"
#include "Commands/SoundHorn.h"
#include "Commands/TeleopDrive.h"
#include "Commands/TeleopLift.h"
#include "Commands/ToggleCompressors.h"
#include "Commands/ToggleLights.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	printf("Entering OI Constructor\n");
	// Process operator interface input here.
	driverInterface = new XBOX360_Controller("Driver",1);

	driverInterface->Assign_ButtonCommand(XBOX360_RIGHT_BUMPER, new NextTube(), ButtonAction_Pressed);
	driverInterface->Assign_ButtonCommand(XBOX360_LEFT_BUMPER,  new PrevTube(),ButtonAction_Pressed);
	driverInterface->Assign_ButtonCommand(XBOX360_X, new ToggleLights(),ButtonAction_Pressed);
	driverInterface->Assign_ButtonCommand(XBOX360_B, new SoundHorn(),ButtonAction_Held);
	driverInterface->Assign_ButtonCommand(XBOX360_Y, new ToggleCompressors(),ButtonAction_Pressed);
	driverInterface->Assign_ButtonCommand(XBOX360_A, new Fire(),ButtonAction_Pressed);
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("NextTube", new NextTube());
	SmartDashboard::PutData("ChargeShooter", new ChargeShooter());
	SmartDashboard::PutData("Release", new Release());
	SmartDashboard::PutData("Fire", new Fire());
    SmartDashboard::PutData("SoundHorn", new SoundHorn());
	SmartDashboard::PutData("ToggleLights", new ToggleLights());
	SmartDashboard::PutData("ToggleCompressors", new ToggleCompressors());
	SmartDashboard::PutData("PrevTube", new PrevTube());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	printf("Exiting OI Constructor\n");
}

XBOX360_Controller* OI::getDriverInterface() {
	return driverInterface;
}
